### ISSUE TITLE
[Bug] GALADE crashes when VS is open but no documents are open

### ISSUE THREAD

**Issue by davidcole1340** [arnab-sen/GALADE#25]
**Current behaviour:**

When trying to connect GALADE to the Visual Studio Debugger while no documents are open, GALADE will crash with the following error:
```
[7:21:30 AM 9/02/2021] Unknown exception thrown: 
-> System.NullReferenceException: Object reference not set to an instance of an object.
   at DomainAbstractions.VSDebugger.<>c.<PresentVSChoice>b__14_0(DTE2 dte) in E:\Code\C#\Projects\GALADE\ALACore\DomainAbstractions\VSDebugger.cs:line 104
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DomainAbstractions.VSDebugger.PresentVSChoice(List`1 candidates) in E:\Code\C#\Projects\GALADE\ALACore\DomainAbstractions\VSDebugger.cs:line 104
   at DomainAbstractions.VSDebugger.ConnectToVisualStudio(Boolean getUserSelection) in E:\Code\C#\Projects\GALADE\ALACore\DomainAbstractions\VSDebugger.cs:line 60
   at DomainAbstractions.VSDebugger.ProgrammingParadigms.IEvent.Execute() in E:\Code\C#\Projects\GALADE\ALACore\DomainAbstractions\VSDebugger.cs:line 40
   at DomainAbstractions.MenuItem.<ProgrammingParadigms.IUI.GetWPFElement>b__9_0(Object sender, RoutedEventArgs args) in E:\Code\C#\Projects\GALADE\ALACore\DomainAbstractions\MenuItem.cs:line 39
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at DomainAbstractions.MainWindow.Run(Application app) in E:\Code\C#\Projects\GALADE\ALACore\DomainAbstractions\MainWindow.cs:line 83
   at Application.Application.Main(String[] args) in E:\Code\C#\Projects\GALADE\GALADE_Standalone\Application\Application.cs:line 79
```

**Expected behaviour:**

GALADE doesn't crash

**Steps to reproduce:**

1. Open VS2019 and select a solution
2. Open GALADE
3. In GALADE: Debugger -> Connect to Visual Studio Instance
4. Crash

**Comment by arnab-sen** [comment]
Issue found in v1.11.0-preview, fixed in v1.11.0.
